### PR TITLE
Fix irregular pads and text alignment

### PR DESCRIPTION
**Pull request by judge2005**
Hi,
Figured I'd submit my changes as a pull request...

### CODE REVIEW

**Comment by lachlanA** [comment]
Hi,   which version of Kicad are you testing with ?
I submitted a bug fix for for text import problems in KiCad's  import,
which fixed a lot of problems.
but it's only in the latest Dev Branch.

Lachlan

**Comment by lachlanA** [comment]
I add your fix,   sorry for the slow response,   I have been away for the last few days,  enjoying the sunshine,     I will give it a test then,   update the comments and  update the eagle-to-kicad  with  this
new version.
Version 5 (dev)   has much better import for unconnected tracks, and via's   so you don't need the hack
I made up for converting via's to pads.

Lachlan

**Comment by lachlanA** [comment]
PS: thanks for the help !

**Comment by judge2005** [comment]
Latest v4. BTW my changes for text weren't to get around issues with text import. The converter was ignoring the text alignment specified in the Eagle file. That's what I fixed.

**Pull request merged**
